version: 0.2

env:
  variables:
    EC2_USER: "ubuntu"               # Change if using ec2-user
    EC2_HOST: "YOUR_EC2_PUBLIC_IP"   # Replace with your instance public IP
    SSM_KEY_PARAM: "/deploy/ssh_key" # Secure key stored in Parameter Store

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y zip unzip openssh-client awscli
  pre_build:
    commands:
      - echo "Fetching private key from SSM..."
      - aws ssm get-parameter --name "$SSM_KEY_PARAM" --with-decryption --query Parameter.Value --output text > /tmp/deploy.pem
      - chmod 600 /tmp/deploy.pem
  build:
    commands:
      - echo "Zipping application..."
      - zip -r artifact.zip ./*
  post_build:
    commands:
      - echo "Uploading artifact to EC2..."
      - scp -o StrictHostKeyChecking=no -i /tmp/deploy.pem artifact.zip ${EC2_USER}@${EC2_HOST}:/tmp/
      - echo "Deploying new release..."
      - ssh -o StrictHostKeyChecking=no -i /tmp/deploy.pem ${EC2_USER}@${EC2_HOST} "bash -s" <<'EOF'
            set -e
            RELEASE_DIR="/var/www/releases/$(date +%Y%m%d%H%M%S)"
            mkdir -p "$RELEASE_DIR"
            unzip -q /tmp/artifact.zip -d "$RELEASE_DIR"
            ln -sfn "$RELEASE_DIR" /var/www/current
            sudo systemctl reload apache2
            echo "Deployment complete!"
        EOF
artifacts:
  files:
    - artifact.zip
